### ISSUE TITLE
Explanation of conditions

### ISSUE THREAD

**Issue by mase76** [renyuneyun/Easer#115]
Hi!
What is the exact behaviour of conditions. Is there a polling rate? What when a condition changes? What's the difference to scenarios?

**Comment by ildar** [comment]
did you grok this: https://github.com/renyuneyun/Easer/wiki ?

**Comment by mase76** [comment]
Yes, but confusing.

**Comment by renyuneyun** [comment]
Like said in the wiki, Condition represents a long(er)-term state; the "Scenario" is a historical name, and can be seen as synonym as "Event" (and I'm planning to change the name to Event some versions later).
One semantics difference when used in Script is: Easer will "listen" to Event/Scenario, but "check" Condition - when a Condition is set, it will keep track of the state, and return the current state when "check" happens. (See the last part for "check" and "polling rate".)

One simple example to show the difference:
Suppose you are moving between two cellular towers, and you have one Condition listening to them and also a Scenario listening to them. (You know the semantics means *either* of them.)
* For **Condition**, it will enter the "satisfied" state only **once**, which is the time you enter the range of the first tower (whichever that tower is), and will keep "satisfied" until forever (because you never leave these two towers).
* For **Scenario**/**Event**, it will fire **every time** you move to the other tower (and also the first time you enter the range of the first tower).

(You may find there is something called "advanced scenario condition" [the word "condition" here doesn't mean that "Condition" discussed above], which is the method used previously to mimic such a behavior, but proven to be a bad attempt. Don't worry if you never intend to use them - I'm considering removing it.)

There is no polling rate yet for any of the Conditions, because they all come from Event, and can use the same mechanism to get real-time (at least as far as Android tells us) updates.
However, as mentioned in the first part, because Easer will (in semantics) keep "check"ing the Condition until satisfied, it is possible for future Conditions to have a polling rate internally (depending on the design of the Condition). We are not yet at that stage, and I think adding a adjustable setting for each of them may be a good choice.
