### ISSUE TITLE
Scenario "Receive Broadcast" can't be saved.

### ISSUE THREAD

**Issue by kaefert** [renyuneyun/Easer#121]
Hello there!
I installed Easer 0.6.3 from F-Droid today, because I would like to use it to process a Broadcast from the application Gadgetbridge when I push a Button on my Mi Band 2 wearable.

Sadly, I can't save the scenario. This is the error I get no matter what I enter in the two text fields Action & Category (although I have no idea what I should enter into Category...)
```
Prevented saving data with invalid field(s).
Please recheck your choices / inputs.
```

Is there a more in depth documentation for that feature than the one sentence included in
https://github.com/renyuneyun/Easer/blob/master/README.en.md
?

**Comment by 413j0** [comment]
Used to work, until at least a couple of monts ago, I also use it for the same thing, but I skipped several versions and I found out after updating that it no longer listens to the broadcast

**Comment by renyuneyun** [comment]
Hi, thanks for reporting!
Sorry for the inconvenience about that wrong prompt... I wasn't aware there is some logic errors there. They will be fixed soon.

**Comment by kaefert** [comment]
F-Droid shows me 0.6.4 as the newest version it has. Where do I get 0.6.5?

**Comment by renyuneyun** [comment]
Whoops, forgot to mention that. Please wait a few days for the new version
to show up on F-Droid.



Thomas <notifications@github.com> 于 2018年6月11日周一 13:01写道：

**Comment by kaefert** [comment]
Okey so the new version reached F-Droid and now I was able to create a Scenario with Action = "nodomain.freeyourgadget.gadgetbridge.mibandButtonPressed" and Category empty (don't know if or what I should put there..)

I created a Profile and a Script to make use of this Scenario, and now when the broadcast is sent by Gadgetbridge (as seen in the Logcat output:)
```
06-18 12:28:24.807  3438  3465 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:25.317  3438  3463 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:25.323  3438  3463 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:25.835  3438 11371 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:25.839  3438 11371 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:26.353  3438  3465 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: button pressed
06-18 12:28:26.356  3438  3465 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: Activating button action
06-18 12:28:26.359  3438  3465 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support: Sending nodomain.freeyourgadget.gadgetbridge.mibandButtonPressed with button_id 0
```

I can see in the Activity Log of Easer that it received the broadcast.


The problem I have now is that I would like to make Easer ring my phone. The only way I deduced from the names of the possible Operations that seems should be able to do that is the "Set Alarm" Operation. I've tried selecting "Relative" and entering Time "0" - But it doesn't want to save that. I also tried "1" for "Time" but that also didn't work. Help please.

**Comment by renyuneyun** [comment]
There are two problems in this case (but none of them relates to this issue any more, horray):

1. Alarm isn't mean to do things like this, though you can try... It may be possible to add a "play audio file" thing, but it is not yet there.
2. Actually you should be able to type 00:00 in this field. The input type is `time`, and the `:` symbol should be one of the options. I just checked two phones with different input methods, and they both works correctly. Probably this is a problem with your input method (or "soft keyboard", in case this phrase is easier to understand).

"Action" and "Category" are both the things used in "Intent" (see [Android document](https://developer.android.com/guide/components/intents-filters#Receiving)). You should be familiar with this if you really intend to use it.

p.s. we'd better not keep this discussion under this issue (because no longer relevant). You may open another issue or continue this in the chatroom (see README).

**Comment by kaefert** [comment]
Sorry, you're right. This issue has been fixed ("Receive Broadcast" scenario can be created and works as expected).

So I guess we can close this issue.
