### ISSUE TITLE
Missing permission for Bluetooth

### ISSUE THREAD

**Issue by jdoe0** [renyuneyun/Easer#13]
According to the [documentation](https://developer.android.com/guide/topics/connectivity/bluetooth.html#Permissions), it is required to have `android.permission.BLUETOOTH` to be able to control Bluetooth at all. This is the case even if `android.permission.BLUETOOTH_ADMIN` is already requested.

Currently, only `android.permission.BLUETOOTH_ADMIN` is listed in `AndroidManifest.xml`. On my phone, this causes the app to crash when it tries to control Bluetooth.

**Comment by renyuneyun** [comment]
Thanks for pointing out :) I'll fix this in the next release (preferrably late this week or early next week).

Android Manifest permission is a myth somehow...
In my phone (as well as the emulator), switching bluetooth on and off works perfectly.
It is also said that app should have `android.permission.MODIFY_AUDIO_SETTINGS` to change ringer mode, but surprisingly many (including me) didn't require that permission and it works... (And from Android 7 on, I need also add `android.permission.ACCESS_NOTIFICATION_POLICY` to make it possible to change ringer mode to Do Not Disturb, which I haven't yet.)

**Comment by renyuneyun** [comment]
It's fixed in v0.3.2.

F-droid build seems to be hanging up again these days, so we may need to wait for a few days before it enters the repo. (If I upload a manual build to somewhere [e.g. bintray] singed by me, the signature checks will fail so you need to uninstall the previous version to install my build. This is not ideal because you will lose all the data of Easer... Though export and import mechanisms are going to be added, they are not there yet.)

**Comment by renyuneyun** [comment]
Closed for now. If it still doesn't behave correctly, feel free to reopen the issue.
