### ISSUE TITLE
[Regression] Ringer -> Sound stopped working

### ISSUE THREAD

**Issue by ildar** [renyuneyun/Easer#141]
After upgrade 0.6.6 to 0.6.7
Can't give you debug logs now, will tomorrow

**Comment by ildar** [comment]
as promised
[logs_0.csv.log](https://github.com/renyuneyun/Easer/files/2187430/logs_0.csv.log)

**Comment by renyuneyun** [comment]
I this this is the same as #143 , so it should also have been fixed.
I'll leave it here, and wait after reporting from #143.

**Comment by ildar** [comment]
Seems to be fixed.
BTW you can put apk on the GitHub itself in Releases

**Comment by renyuneyun** [comment]
Yes I'm also thinking to upload it there.
Two things are preventing me from doing this:

1. how to do that automatically in a script (though API, probably)
2. how to attach release note automatically

The second problem can be almost solved after #116 , since each version will have their changelog separated afterwards (so a simple `cat` will work).
