### ISSUE TITLE
No function anymore

### ISSUE THREAD

**Issue by mase76** [renyuneyun/Easer#143]
Hi!
The app does not work anymore since 0.6.7. No profile shown as loaded by no script. I did a data conversion before.

**Comment by ildar** [comment]
Could you please turn on logging and attach the log?

**Comment by mase76** [comment]
Here is the log.
[logs_0.txt](https://github.com/renyuneyun/Easer/files/2189947/logs_0.txt)

**Comment by surferjoeit** [comment]
Hello,
the same for me. Before installing 0.6.7.1 all was fine, now some profiles doesn't work (others work fine).
In detail: i have a script that launch a profile when i'm connected to a particular wifi network, This profile should launch an app but it doesn't work anymore since latest relelase (0.6.7.1). I converted data, of course.
Thanks

**Comment by ildar** [comment]
Non-working Ringer settings already reported:
https://github.com/renyuneyun/Easer/issues/141

**Comment by surferjoeit** [comment]
Thanks.
Log attached anyway


[logs_0.zip](https://github.com/renyuneyun/Easer/files/2191912/logs_0.zip)

**Comment by renyuneyun** [comment]
I think I figured out the problem, and this should have been fixed in v0.6.7.2.

Please have a test and report back.

(You can also try [the apk signed by me](https://bintray.com/renyuneyun/Android/download_file?file_path=Easer-v0.6.7.2.apk), but be aware how Android deals with apks with different signatures.)
