### ISSUE TITLE
let us choose language

### ISSUE THREAD

**Issue by FadeFx** [renyuneyun/Easer#175]
To easier communicate about problems in the app, you should give us option to change interface language independently to system language, this way we could switch to English and we can be sure to talk about the same thing.

**Comment by naodesu** [comment]
I can't use this app, because translation to Russian is horrible (it is auto-translated?) and I can't understand UI at all.
Switching to English will solve the issue for me.
![Screenshot_2019-05-07-04-48-31-637_ryey easer](https://user-images.githubusercontent.com/38212/57261976-98e9da00-7083-11e9-983e-4ee834721acc.png)

**Comment by ildar** [comment]
IIRC there's an Xposed module for that.

**Comment by renyuneyun** [comment]
Forgot to mention: v0.7.5 allows manual selection of language (locale). You should be able to choose whatever language you prefer (or simply use system's strategy) as long as there is one.

I'm closing this issue. If there are any bugs, please open a new issue :)

**Comment by renyuneyun** [comment]
@ildar Yes I also remember one, but forgot the name (something like App Tune?)

@naodesu Sorry about the translation quality. The translation is hosted on weblate (see [thie part of README](https://github.com/renyuneyun/Easer/blob/master/README.en.md#help-translating) for more information), and is translated by volunteers. Unfortunately I don't know speak a lot of languages (only Chinese and English), so most languages are used as is.
If willing, you can help improve the translation :)
