### ISSUE TITLE
Uniq cell location

### ISSUE THREAD

**Issue by Vintic** [renyuneyun/Easer#177]
In condition section - same cell location can be added multiple time.(wrong)
In event section - same cell location can be added only single time.(correct)

**Comment by spaetz** [comment]
Sorry, I think there is amisunderstanding here. It is OK to add multiple cells to a condition, but it does not make sense to be able to add 'the same cell number' multiple times to the same condition. Or is there any use case for that? this is now possible, unfortunately.

**Comment by renyuneyun** [comment]
@spaetz IIRC, that previous case was complaining about not working, because he/she was adding the same cell-location and didn't see a "new" one added.
It's just so different of everyone's mind, so I finally just made it clear that this is not working... At least a "redundant" thing can be picked up, but people may not know how a "missing" one may be still correct...

Anyway, I think the scanning-adding way (#125) can reduce the problem, and I can then ensure the list is no-redundant.

**Comment by renyuneyun** [comment]
Since #125 is closed. I assume this can also be closed?
