### ISSUE TITLE
[RFE] (allow to) Lower the priority of the permanent notification

### ISSUE THREAD

**Issue by genodeftest** [renyuneyun/Easer#185]
With the latest update, Easer got a permanent notification entry. In the default state, it is being shown in Android's top bar, which is not necessary in my opinion. Other Apps like NetGuard, DAVdroid or Telegram allow to reduce the notification priority so that the notification is not showing an icon and also only listed as a single line in the expanded system menu. This feature would be nice to have in Easer too.

I'm using Easer 0.7.0.3 on Android 8.1.0.

**Comment by renyuneyun** [comment]
Hi, as you may already see, v0.7.0.4 has an option to enable/disable the notification entry.
The indicator notification priority in v0.7.0.4 is trying to be as small as possible.

But if you are using Android 8+, it has to be there in the bar, because of the stricter rule of Android 8. (I think NetGuard behaves the same from my test just now, on Android 8.1; I do not use telegram any more (because it requires phone number), so I can't tell if there is any difference, but I don't think there will be, because this rule is very strict.)

Just in case: do you / anyone consider it necessary to have an option to set the priority of the notification?

**Comment by genodeftest** [comment]
Thanks, the way it is implemented in v0.7.0.4 is working fine for me. I don't need more options on the notification.
