### ISSUE TITLE
Events do not trigger unless 'refresh' is pressed

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#20]
Android version: 7.1
Device: Nexus 5x
Easer version: 0.3.3 (from f-droid)

I have created a super simple way to reproduce this behavior:

1) Add a profile that enabled bluetooth (and nothing else)

2) Add an event that triggers on "Battery Status" -> Is Charging

3) Plug in device to power so that it is charging.

Expected behavior: Easer enables bluetooth

Actual behavior: Nothing happens. If I load Easer and hit the 'refresh' floating button, then it triggers and enables bluetooth. I have tried the following and the behavior does not change:
- Waiting several minutes for it to trigger
- Enabling permission for Easer to set system settings
- Disabled battery optimization for Easer

None of those actions resolve this issue.

I have tried monitoring logcat to see if anything useful is printed, but logcat is super noisy when this chain of events if happening. If there's a specific tag/filter I can apply to logcat to show only messages from Easer, then please let me know what that is so I can (hopefully) collect useful information for you!

This may be an unrelated issue, but if I leave the device plugged in/charging, and disable bluetooth and hit the 'refresh' button in Easer again, then Easer will re-enable bluetooth. This seems to happen every single time I hit refresh, even though the 'charging' state never changes (i.e. it is always charging)

**Comment by renyuneyun** [comment]
Whoops, thanks for reporting!

I haven't really tested, but I think it is possible that I used the wrong / incomplete intent filters for `BatteryEventPlugin` (so Easer didn't receive that Broadcast and won't perform actions).
Unfortunately, I don't think there is a way to get this information because we can't know if the code missed something (not catching an Intent / Broadcast) (unless we can know which Broadcast is on the way in Android system's view). Appreciate a lot for your willing to help :)

p.s. As of battery status, waiting for a while shouldn't be needed unless the device is extremely slow :P

Indeed, the second problem is annoying. I'm planning to get rid of that (by implementing #19), but unfortunately that behavior is going to be changed only after #19 is done. (Though it is possible to get rid of that now, it requires external storage or an extra dedicated component, and they will be dropped/removed when #19 is done.)

**Comment by renyuneyun** [comment]
707f98825eddf6ec942ca118024506a06d1b08ca should have fixed the first issue.

Please report back after you have a try :P

**Comment by craftyguy** [comment]
Cool, thank you! I will not be able to test this until the new version is picked up by f-droid.

**Comment by craftyguy** [comment]
This appears to be resolved now, thank you!
