### ISSUE TITLE
Data not converted from 0.7.6.2 to 0.7.8-beta

### ISSUE THREAD

**Issue by racuna** [renyuneyun/Easer#241]
After update and apply "Data Conversion" some scripts are missing:

- check if the phone is connected to any network to enable sync, or disable sync if the phone is not connected. This script help me a lot saving battery when I'm traveling or hiking.
- check if the phone is connected to any wifi also to enable sync or launch backup apps

In the profile section this were not converted:

- launch app

Conditions not conveted:

- bluetooth connection check
- wifi connection check
- data connection check

**Comment by renyuneyun** [comment]
Thanks for reporting.
The most wierd thing is how could you make Easer "update" from v0.7.6.2 to v0.7.8-beta... All *beta* should have a different application id which makes them *separate* from the non-beta ones.
Do you mean the following:?
1. install v0.7.8-beta
2. import data
3. convert data

**Comment by racuna** [comment]
Yes, import from Google Drive and then convert

**Comment by renyuneyun** [comment]
Thanks. Now I understand.

I can see why the "connectivity" things are not converted. That's fixed in v0.7.7.7 and also v0.7.8-beta**2**.

But I don't see why "launch app" is not converted... Were there a crash/error log produced by Easer (located under `/sdcard/logger/error/`, if you have "external logging" enabled)?

**Comment by racuna** [comment]
Hi again.

I installed 0.7.7.7. Everything was correctly converted, except for launch
app profile.

I tried to add it, but I can't. I only have the package name, but not the
class. I leave that field blank and then I saved it, but doesn't work.

Maybe that's the problem?

Regards

**Comment by renyuneyun** [comment]
So, what was the launch app operation you were using?
(E.g. the app name, etc...)

**Comment by racuna** [comment]
There is an app to backup photos (degoo), something as an alternative to
Google Photos. But, in order to save battery I want to launch the app only
at night, when the phone is charging and connected to a Wifi.

The apk name es com.degoo.android

**Comment by renyuneyun** [comment]
Ok, so does this app have multiple entry points (i.e. icons in the launcher / app drawer)?

The reason there is an "package id" and "class name" is because some apps have multiple entry points, so with the package id alone it won't launch -- the class name (of the desired entry) should also be specified to make it work.

To figure out the class ids, currently you have to seek help from other apps (or command line / adb if you know how). I only had experience with one app a few years ago, so I'll not make any suggestions.
(A long-term plan of Easer does include the support of picking them directly instead of filling in manually.)

(I assume this Launch App action never worked for your case in Easer, even on 0.7.6.2. If not the case, please do shout out.)

**Comment by twikedk** [comment]
To me it looks like that at least the import is working now, running version 7.8. And it also looks like all my data is working too.
