### ISSUE TITLE
Crash when entering text in Cell Location field

### ISSUE THREAD

**Issue by perepujal** [renyuneyun/Easer#28]
I want to enable/disable data roaming, (or just data) when entering/leaving a country, I live near the frontier to 2 other countries, for one I get no data roaming charges at all but for the other I get very very expensive charges for data roaming, so I tried to use the Cell Location field putting there the country code, or the phone company name, the result is a crash when saving the event.

[logcat-crash-Cell-Location.txt](https://github.com/renyuneyun/Easer/files/1240289/logcat-crash-Cell-Location.txt)

Note that the above logcat is for when entering letters in the cell location field, if instead I enter digits and the entered number is 1234 the crash tells about Array Index Out of Bounds.

What is the accepted format for the Cell Location and where to find the right values?

**Comment by renyuneyun** [comment]
Hi, sorry for the inconvinence of the UI design.
The actual intention is to use the "pick" button (to the left of that text box) to "add" the current "position".

The "correct" format is a dash separated field with a number on either side, eg 2838-123. The numbers are the identifiers of the base station, so is not intented to be directly / manually entered by the users - that's why the pick button is there.
In some situations (which I have observed, but not well understood), the identifier of the base stations may change (or maybe the base stations are switched on and off in turn?). You may need to re-add the new ones to the list.

Also notice Easer currently runs as a non-system and non-root app, so the function to switch the data on / off may not work on some devices (e.g. my phone, OxygenOS 3.1.4 based on Android 6.0.1).

p.s. Suggestion on the usage: I'm not sure how the operators determine where you are currently in, though I feel it is quite possible they use base station. If this is true, then using this functionality is the right choice; however, if it's not, you may need to rely on other options (e.g. GPS location which would probably be added in future releases of Easer).

**Comment by perepujal** [comment]
Oh, understood, thanks.
In my phone I had to add the MODIFY_PHONE_STATE permission and in plus move easer to be a system app to be able to turn on and off data usage.

Thanks for commenting about base station changes, I'd never thought about that, will see how long takes to get all the interesting ones picked

Phone companies charge if you connect to their service, disregarding where you are, so GPS location will not help, maybe company name...
