### ISSUE TITLE
[Q] community development / chat

### ISSUE THREAD

**Issue by ildar** [renyuneyun/Easer#297]
I suggest opening a chat room for a couple of reasons:
1. with Beta version(s) I guess that Rui wants to have feedback fast
2. users often want fast hints / support
3. or share their experience

If reasons are good enough then Rui please choose the communication platform you like. My humble survey of such (only open platforms here):
1. IRC: classical yet a bit imperfect, e.g. misses the feature of the room history
2. Matrix inherits IRC, very much universal, having bridges to many other platforms
3. Gitter is good and allows using github (and some other) accounts.

**Comment by renyuneyun** [comment]
Thanks for providing a voice :)

Actually there is a matrix room, as you can see in the second line of README.
This room has an IRC (`freenode.net`) bridge set-up, though the channel name (`#easer`) is not added to the badge list (because I didn't find a good badge for IRC channel...).

I had a thought about gitter, but then thought it's mainly for development (and closed-source), so better not to have it for users to avoid confusion.

**Comment by ildar** [comment]
Sorry for being so blind )))
joined 👍
