### ISSUE TITLE
Add a event for "under operation"

### ISSUE THREAD

**Issue by ramack** [renyuneyun/Easer#36]
Allow easer to trigger an event when the phone gets/stops getting used. Maybe the simples idea would be to check for a locked screen.
E.g. disable WIFI and mobile data completely, as long as I am not using the phone.

**Comment by renyuneyun** [comment]
I'm also wondering that -- actually one of the initial target that I started to write Easer is to do this kind of thing (and save battery).
The problem is how to define "use".

Personally, I would prefer to decompose this into many smaller components (e.g. unlocked the phone or opened the screen) and let the users to define it themselves.

Another similar feature request is #16 , which may be a better way of the goal (at least for my goal in the beginning) because the Android system could turn wifi (and maybe also mobile data) off after the screen is off for several minutes.

**Comment by ramack** [comment]
#16 is more about time as a trigger l'd say here I mean using the phone. Locking and unlocking the screen is already quite close. The only case that comes to my mind where use and screen lock might be different is when we are e.g. in a camara APP preventing the screen to lock, but as soon you leave that camara APP the screen gets locked. So the question is more what the API provides in these cases and how do name the events and document that the behavior is clear for the user...

**Comment by renyuneyun** [comment]
@ramack Good point... I'm always wondering whether the functionalities are easy to understand or not, but have no idea how to gather information / feedback.
The only thing I did is the wiki, but not everyone like (or know) to read the wiki though...

By the way, would you like to give some opinions to #19? It could be useful for defining the actual condition of "using phone".

**Comment by natrius** [comment]
I am not sure if i understood it correct, but why not an option "Screen locked for: x Minutes". Kind of something like that, so with one Minute it does not trigger the scenario (?) when i accidentaly press the "lock" button.
