### ISSUE TITLE
Add profile alarm and event from notification

### ISSUE THREAD

**Issue by subiol** [renyuneyun/Easer#43]
First, I want to thank you for this project. Android needed an open source "Tasker".

A couple of suggestions:

1. Add a profile that allows to trigger an alarm. I dont know if this can be done through Intent or it needs its own setup.

2. Event that triggers from notifications. Ideally you can filter the notifications by program that emitted the notification and by content of the notification (f.e. the notification contains certain word)

**Comment by renyuneyun** [comment]
Hi,
Glad you like Easer.
I haven't really used Tasker yet but have heard about it a few times. Are there any concise videos / recordings exmpaining its functions (the app introduction is not enough for me to complete understand what it can and can't do)? (Just for curiosity, no need to reply :)

For the notification event: Yeah, I'm also planning receiving notification to be implemented in the next few releases :)

For the "alarm" operation: I can think of three kinds of "alarm"s: ring bell, notification and popup. Which one do you mean?


p.s. I'm also planning the notification feature (hope it could come together with listening for notification events).

**Comment by subiol** [comment]
I don't know any Tasker video, but I'm sure there has to be something on YouTube.

Great to hear the notification event is planned.

The alarm I am looking for is a ring bell. One thing I did with Tasker was add a tag in the comments to some of my calendar events. For example, #wake1 or #wake2. When it was detected that I had added such calendar entry, Tasker would set up an alarm for 1 or 2 hours before the event started. That way I did not have to worry about setting alarms for each day. Depending on my calendar activity I would get the appropriate alarm and wake on time to get ready and go. Just an example, probably there is still some way to get here, for now an alarm operation would work wonders.

**Comment by renyuneyun** [comment]
The functions to listen to notifications and set alarm are implemented in v0.5 :)
(Thought due to a strange f-droid bug, the date when v0.5 enter the repo is unpredictable... Maybe a few days later, maybe weeks...)

Combining a "notification" event with a "set alarm" operation should work properly for the senario, though I haven't tested this use case.

I'm closing this issue. If any of these two functions don't work well, feel free to open a new issue (but not reopening this one since they are different issues).
