### ISSUE TITLE
Ringer mode in profiles broken

### ISSUE THREAD

**Issue by ildar** [renyuneyun/Easer#45]
Version 0.4.7 F-Droid

**Comment by renyuneyun** [comment]
I just tested it, and it works both on the emulator and on my phone, OxygenOS 3.1.4 (Android 6.0.1).
Could you provide more information (e.g. phone model / ROM version / system version)?

**Comment by ildar** [comment]
Weird.
I tried two phones with Android 6. When I choose "Ringer mode" it sends me
to the Notifications permissions for apps (no difference if I gave Easer
the permission or not). It showed kinda "Sound/Vibra/both/none" in prev.
versions.
Cleaning app data doesn't help.

**Comment by renyuneyun** [comment]
That's fixed now (v0.4.9) ;-)

It's because Android doesn't really give `BIND_NOTIFICATION_LISTENER` permission to app context, so the check always returns false. I moved to a different way to test the permission and it should work without any problem.

(It's also weird why my phone doesn't tell me the permission issue...)
