### ISSUE TITLE
Add option for detecting headphone plug/unplug events

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#48]
Since the media play/pause is implemented, having a way to trigger on headphone plug/unplug would be great! Some media players don't have an option for automatically playing when headphones are inserted, or maybe I would want to set a different ringer mode when headphones are unplugged.. etc.

**Comment by renyuneyun** [comment]
Definitely. That will be implemented shortly after.

I originally thought this event could be done by filtering only actions and categories of the broadcast, but [it seem I'm wrong](https://developer.android.com/reference/android/media/AudioManager.html#ACTION_HEADSET_PLUG). Since currently there is no plan to add general broadcast event, it will be implemented as a separate component.

**Comment by craftyguy** [comment]
You are awesome! Thank you!
