### ISSUE TITLE
Consider accepting donations over librepay?

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#49]
Hi! This app is extremely useful (I've been hoping for a FLOSS IFTTT thing for years..). It looks like you only accept donations via bountysource.com, which is rather unfortunate!

Have you considered a freedom-respecting platform like [librepay](https://liberapay.com/about/)? quite a few FLOSS projects use this.

Also, for what it's worth, it looks like bountysource.com was just acquired by some buzzwordy blockchain company called Canya.io... I definitely don't want to sign up for bountysource now.

**Comment by renyuneyun** [comment]
Wow, thanks for the info. I didn't notice bountysource was recently acquired. How is the company (Canya.io)?

Actually I investigated (well, read the descriptions, etc) some platforms some time ago -- librepay is on that list. Every platform has their shortcomings, and none of them fully satisfies me (only considering functionality). Bountysource was the best match during that time, that's why I chose it (however, the lowest limit of 1$ is the biggest aspect I don't like).
I'll explore more recently when I have time. Registering an account doesn't take much time, but I'd prefer not to blindly register everywhere.

(Currently I'm cleaning up the code and considering the way to better express the type of events for easier understanding, better controlling from the user side, and easier maintainance.)

**Comment by renyuneyun** [comment]
The lower minimal amount really seems to be a good choice (at least as a complementary).

Since the "team" page doesn't fit the current status of Easer (i.e. not a github team because the name has been occupied [though that project seems to be discontinued and I couldn't get in touch with the owner]), I created a personal page.

For anyone interested, the page is: https://liberapay.com/renyuneyun/ . Kindly appreciate any support :)

(LOL, we were both wrong about the name -- it's "liberapay", not "librepay".)
