### ISSUE TITLE
Easer claims not to have all permissions.

### ISSUE THREAD

**Issue by hrittich** [renyuneyun/Easer#51]
When I want to add a profile that changes the "Ringer Mode", a dialog opens which shows that I have granted access to " notifications". I press back, but no entry is added to the profile.

**Comment by hrittich** [comment]
I am running Android 7.1.2.

**Comment by ildar** [comment]
https://github.com/renyuneyun/Easer/issues/45

**Comment by renyuneyun** [comment]
It's a known bug and as pointed by ildar (Thanks, @ildar :) ), and it has been fixed in v0.4.9.

However, due to an unknown problem in the f-droid build server, recent build attempts (of Easer) all failed and we are waiting for their success.
I'm planning to upload self-signed versions to somewhere, which will appear shortly after.

Note: Apps singed by different people/keys (e.g. *f-droid build server* and *me*) can't be directly "updated" by installing another apk because of the security mechanism of Android. The only way is to uninstall and install again. That will cause data loss, but you can use the "export" mechanism in Easer before uninstall and "import" after install to workaround this problem.

**Comment by hrittich** [comment]
@renyuneyun Thanks for the quick response.
