### ISSUE TITLE
Add option for 'events' to be based on actual events, and not continuous behavior

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#55]
The way that 'events' are implemented now seems to result in an event triggering quite regularly even if there were no change in the state that the event is 'monitoring'. Let me explain with an example:

I create an event that runs some profile based on 'battery status: is NOT charging'. The profile that runs turns off bluetooth. Now, if my device is not charging and I manually turn on bluetooth, easer will turn it off after some amount of time. Instead, the event should only run once (e.g. power cord disconnected and no longer charging) and not execute continuously while 'not charging'.

This would allow users to temporarily override Easer behavior without having to outright disable/stop Easer (which means Easer is now unavailable to process other, new events that might happen).

Another example is a profile that enables 'vibrate' ringer mode when connected to a specific wifi network (the event). I may want to enable a different ringer mode on this network (e.g. 'do not disturb') at one point, but Easer will revert my manual config change to 'vibrate mode'.

Ideally, an event would happen once (e.g. 'device is now connected to wifi network X' or 'charging cable has been unplugged and now device is not charging), and the associated profile with the event would be run once. Users could then temporarily override it if necessary.

Please let me know if you need any more clarification about what I am asking for. I have a long history of using IFTTT apps on Android (llama, tasker, automagic), and what I am describing has been the way that all of the ones I have used have all behaved :)

**Comment by renyuneyun** [comment]
Yes, I completely agree.
The [prospective plan of v0.5-v0.6](https://github.com/renyuneyun/Easer/projects/5) has one card/reminder of doing this. I described this as a boolean, "repeatable".
Some events have the nature of being retriggered, and that's why this was not presented in the beginning.

I'm working on splitting Events to Scenarios + Event Logics, and it should be the most important change in v0.5.3. Adding the "repeatable" switch to the new events (in Event Logics) is what I'm planned (in v0.5.3 if everything is as expected, v0.5.4 or v0.5.5 otherwise).

(Better name for everything is welcomed :P)

**Comment by craftyguy** [comment]
I can certainly help with trying to come up with better names :)

So it seems that there are the following 'items' in the app:

- **action**: something (e.g. toggle setting) to 'do'

- **event** (or **trigger**, or **condition**): something that causes the app to perform some action(s)

- **profile**: a group of specific actions to be run in a specified order. A profile is associated with an 'event' that causes it to be run

Some other IFTTT apps I've used allow you to create an 'action', like "set volume to 50%". Then you would create a 'profile', select a trigger/condition (or set of triggers/conditions like 'if connected to this ssid and if bluetooth is on and if charging', etc), and then define a set of actions to be executed when the condition(s) are met.

**Comment by renyuneyun** [comment]
It seems the most puzzling part is the name of "profile"... Just like what you said, some apps I used before use this term to describe a combination of conditions and actions, but it means a different thing in Easer (and I have to admit this name may be a bad one).
For the idea behind the name "profile" in Easer, I only want to describe a "collection"/"bundle" of operations (or "actions" in your naming).

Personally, I'd prefer to describe the "logic" in events, so that one can easily "attach" something to (any of) the existing events. Therefore, it's easier for "you" (user) to understand what "you" (user) have described (/set) in Easer.
The current tree-like way of organizing events is a preliminary way of enabling logics. Thought it's preliminary, it's enough for most cases.

**Comment by renyuneyun** [comment]
v0.5.3 is out :P

This version includes both the ability to set reusable events (called scenario), and the ability to alter whether an event is "reverse" to its scenario (e.g. boolean "not"), is "repeatable" (meaning that when it is already true, it can still be triggered [i.e. to load the profile another time]) and/or is "persistent" (meaning that when an event is set to true, it will never be set to false afterwards [though there is some glitch currently when you interacting with the UI])).
