### ISSUE TITLE
F-Droid build failure - solved

### ISSUE THREAD

**Issue by fengshaun** [renyuneyun/Easer#57]
FDroid build has been failing since 0.4.7. It's generally a good idea to follow up with recurrent build failures as there may be a soluble cause.

In this case, it seems android-27 is not getting downloaded automatically...or something of that nature.

The issue is fixed now. See https://gitlab.com/fdroid/fdroidserver/issues/445 and https://gitlab.com/fdroid/fdroiddata/commit/2fffc59b for further details.

**Comment by renyuneyun** [comment]
Thanks for letting me know it's solved :)
Glad they finally figured out the problem.

I was tracking the problem since the first failed build (see the forum post and reply [here](https://forum.f-droid.org/t/connection-refused-during-building-process-in-official-fdroid-server/1743/7) and [here](https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195/56), and also #53 ), but wasn't looking at it in recently.
Indeed the commit Marcus made opens my idea of how to (slightly) alter the f-droid build process.

I'll close this issue after they are successfully rebuilt.
