### ISSUE TITLE
Update F-droid repository

### ISSUE THREAD

**Issue by Volodumur558** [renyuneyun/Easer#59]
There is only a buggy 0.5.3 release on F-droid. Good 0.5.3.1 and 0.5.3.2 are not yet there

**Comment by renyuneyun** [comment]
I was also thinking why the newer version wasn't indexed by f-droid automatically (since the log shows v0.5.3.1 is published before v0.5.3 is fetched by f-droid).

Anyway, the f-droid repo should be updated automatically a few days after a version is published (here). The delay is caused by the workflow and number of apps to build on their build server side.

According to the log, v0.5.3.2 has been built on the server. It should appear in the repo quickly (within one day usually). (Though v0.5.3.1 is missing...)

**Comment by Volodumur558** [comment]
Thank you, now it is there
