### ISSUE TITLE
App crashes while we try to import a zip file

### ISSUE THREAD

**Issue by syedubair** [renyuneyun/Easer#65]
#### Expected behavior
App should behave normally and import as we try to import a  .zip file. 

#### Actual behavior
When we try to import and press a zip file the app crashes 

#### How to reproduce
Download [Easer]( https://f-droid.org/app/ryey.easer). 
Launch the app. 
Go to menu and press settings. 
Now click on the import option in data manage section. 
Search and select a .zip file from memory. 
Click on the .zip file. 
The app crashes. 

* App: Easer v0.5.5
* Operating system: Android Nought 7 - Moto g5 plus 

#### Recording Of The Bug
https://youtu.be/0fsTTXbBgmQ
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/app-crashes-while-we-try-to-import-a-zip-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pikim** [comment]
Is the content of the zip file correct? I also had the problem when I didn't respect the desired folder structure.

**Comment by syedubair** [comment]
Yes the zip file is fine

**Comment by renyuneyun** [comment]
Just to make sure: since you are also reporting #66, I guess you are not using an (Easer) exported data file. Do you constructed that zip file (which you are trying to import) manually or is that some "random" zip file?
Note that `.zip` is just a common file format and I'm using it **for convenience** as the format of Easer's importing and exporting data; it does **not** necessarily mean that any `.zip` file is a valid file for Easer to import.


Though, this does remind me that I should do a check before really trying to import...

**Comment by syedubair** [comment]
But the app shouldn't crash anyway. It should pop up some messages that
you've selected a wrong file or file can't be imported. The crash should be
fixed first.

**Comment by renyuneyun** [comment]
Yes I agree -- that's what my last sentence was meant.
I think I'll fix it in (or before?) v0.5.6 .

**Comment by syedubair** [comment]
Happy to hear :)

**Comment by renyuneyun** [comment]
v0.5.5.4 should have solved this problem.

I have to admit I use a workaround which in theory doesn't always produce the result. But I believe in most cases (>99%) it shouldn't be a problem, unless deliberately.
