### ISSUE TITLE
Bluetooth headset action

### ISSUE THREAD

**Issue by mase76** [renyuneyun/Easer#85]
Hi!
Should the heaset plug / unplug action also handle bluetooth headsets, or is this for wired headsets only? I'd like to handle the disconnection of (any) bluetooth headset. After disconnection I want to check the cell location to select a profile.The thing is, when I disconnect from my car, I want to check my cell location to select my home profile or an other location dependend profile.
I tried an event (with scenario) connection type, none, bluetooth, but this does not work. Also not working with headset disconnection. I named it "bluetooth disconnect" and set it as parent of the cell location event. I suppose, that a parent acts like an "and". A reverse scenario is a " not".
The functions are not documented very well. What is the difference between volatile and persistent?

**Comment by renyuneyun** [comment]
Yes, the headset event is supposed to handle wired headsets only (at least, IIRC, the Android API document says so), so you have to use the bluetooth event.

The "none", "after", etc. things belong to an old mechanism called `EventType`. It is expected to be removed in v0.5.7 (as said in the welcome screen), and it has been disabled since v0.5.5+ (but the UI wasn't updated) in favor of advanced Scenario conditions (e.g. volatile, reverse). The "none" should be replaced with "reversed" (see [this wiki page](https://github.com/renyuneyun/Easer/wiki/Replace-Event-Types-with-advanced-Scenario-conditions)).
You are right about "and" and "not", hooray :) (Yes the documentation is not so good. I still have some doubt about the current implementations, and am thinking about other better ways, if any, to be implemented in the future... But, if I'm correct, the wiki can be edited by everyone, so you are more than welcome to complement anything :))

*Volatile* means the Event will go back to *unsatisfied* state when the condition doesn't met (and go back to *staisfied* when the condition met again); *persistent* means it won't (i.e. it will keep the *satisfied* state).

In theory, your way of chaining events (i.e. the "parent") will work if you don't run Easer in passive mode (a setting); if you run it in passive mode, the second event (i.e. cell location) will only **listen** (for new cell location changes) when the first event is satisfied (so you need to set the cell location event(s) as the parent, and bluetooth as the child in order to comply with your needs in passive mode).


p.s. I'm planning to add a companion to Event -- Condition (name not yet sure), to represent the "state" (e.g. location) but not the "change" (which is what "Event" is supposed to represent, in passive mode); this should drop the need of active mode (i.e. not passive mode).
This mechanism should make things more natural in passive mode (e.g. in your example, bluetooth is the parent, and a "Condition" of cell location is the child).
It's in a preliminary stage, but will come to Easer in the future (hopefully not too far).

**Comment by renyuneyun** [comment]
Closed as of not a bug and inactive.
