### ISSUE TITLE
Support for CM/Lineage profile switching

### ISSUE THREAD

**Issue by ghost** [renyuneyun/Easer#89]
This feature would be nice and would allow to enable/disable lockscreen.
Here is link for source code of application with which you can switch CM profiles through widget. https://kaffeemitkoffein.de/source/LChangeProfiles_source.tar.gz

**Comment by bege10** [comment]
Just switching to a LineageOS profile would be much easier than to define many profiles in Easer. LineageOS profiles combine volume, bluetooth, wifi, brightness and many more.
+1

**Comment by renyuneyun** [comment]
@bege10 You can define multiple operations in one profile in Easer. Just curious why would you consider it less easier in Easer?

(I admit reusing an existing mechanism is good and easy.)

**Comment by bege10** [comment]
You are right. But I defined all the profiles already and would prefer not to do it again in Easer - and not to do it twice each time I change a profile.
Anyway, I just started working with Easer and it is fantastic. Thank you very much.


-------- Ursprüngliche Nachricht --------
Von: renyuneyun <notifications@github.com>
Gesendet: 22. Juni 2018 17:53:51 MESZ
An: renyuneyun/Easer <Easer@noreply.github.com>
CC: bege10 <bege10@t-online.de>, Mention <mention@noreply.github.com>
Betreff: Re: [renyuneyun/Easer] Support for CM/Lineage profile switching (#89)

@bege10 You can define multiple operations in one profile in Easer. Just curious why would you consider it less easier in Easer?

**Comment by renyuneyun** [comment]
After a long delay, this is finally implemented as a Remote Plugin. See [this repo](https://github.com/renyuneyun/EaserPlugin-LineageProfileSwitch) ([download here](https://github.com/renyuneyun/EaserPlugin-LineageProfileSwitch/releases)).

I'll add it to f-droid later, after considering remote plugin interface steady. (I'll also add it to bintray.)

Remote Plugin is introduced in v0.7, but I'd suggest wait until v0.7.0.2 to try it out, because v0.7.0.2 has a fix for empty data crash.
